ifndef::imagesdir[:imagesdir: ../images/out]

[[section-context-and-scope]]
== Context and Scope

This section describes who uses {project-name} and what external systems it interacts with.

=== Business Context

image::business-context.svg[]

.User
A fitness enthusiast uses {project-name} to log their strength training workouts and receive AI-generated workout plans.

.Admin
An admin manages the list of exercises available to users.

.AI Engine
The free Gemini API will be used with developer-authored prompts for each type of supported analytical query (ie to generate a summary of the workout or to provide recommendations for the user's next workout).


=== Technical Context

image::technical-context.svg[]

.Backend (fitness-tracker::api)
The backend runs as microservices within a local kubernetes cluster. REST endpoints are exposed over HTTP for the frontend. The backend will make HTTPS requests to the Gemini API using an API Key.

.Frontend (fitness-tracker::web)
The React frontend runs in a web browser. It communicates with the backend over HTTP. It will service both Admins and Users.

.Google Gemini API
The backend makes HTTP requests to Gemini's REST API supplying a prompt along with the workout payload to generate workout analysis and recommendations.
