ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Context and Scope

=== Business Context

TODO: diagram with fitness-tracker, user, admin, Recommendation Engine

.User
A fitness enthusiast uses fitness-tracker to log their strength training workouts and receive AI-generated workout plans.

.Admin
An admin manages the list of exercises available to users in the system.

.AI model
TBD: what AI model receives generated prompt


=== Technical Context

TODO: diagram with fitness-tracker::api, fitness-tracker::web, fitness-tracker::mobile, Gemini API

.Backend (fitness:api)
The api runs as microservices on docker containers. It exposes REST endpoints over HTTP for the frontend and other clients to interact with. It makes HTTP requests to Gemini REST API.

.Frontend (fitness:web)
The React frontend runs in a web browser. It communicates with the backend over HTTP. It will service both Admin and Users.

.OpenAI API
The backend makes HTTP requests to OpenAI's REST API to generate workout analysis and recommendations.
