apiVersion: v1
kind: Service
metadata:
  name: accounts-db-service
spec:
  type: ExternalName
  externalName: postgres-accounts.internal
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-db-service
spec:
  type: ExternalName
  externalName: postgres-fitness.internal
---
apiVersion: v1
kind: Service
metadata:
  name: auth-cache-service
spec:
  type: ExternalName
  externalName: redis-cache.internal
---
apiVersion: v1
kind: Service
metadata:
  name: notification-db-service
spec:
  type: ExternalName
  externalName: mongodb.internal
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-queue-service
spec:
  type: ExternalName
  externalName: localstack.internal
---
apiVersion: v1
kind: Service
metadata:
  name: cleanup-queue-service
spec:
  type: ExternalName
  externalName: localstack.internal
---
apiVersion: v1
kind: Service
metadata:
  name: notification-queue-service
spec:
  type: ExternalName
  externalName: localstack.internal